### ISSUE TITLE
AvanceDB not found in homebrew

### ISSUE THREAD

**Issue by eallik** [RipcordSoftware/AvanceDB#70]
the README has:

> Via the magic of Brew you can spin up an instance of AvanceDB on OSX too. If you are running Windows you are out of luck, at least for the moment.

but...

```
~$ brew search avancedb
No formula found for "avancedb".
==> Searching pull requests...
~$ brew search avance
No formula found for "avance".
==> Searching pull requests...
~$ 
```

**Comment by AppleWatchHipster** [comment]
I get the same result.  Craig is travelling this week hence slow reply.

**Comment by craigminihan** [comment]
@eallik You have to *build* AvanceDB on OSX. Brew is required to install the correct tools to do this, the wiki page explains it all: https://github.com/RipcordSoftware/AvanceDB/wiki/Building%3A-OS-X-10.10.

There is a caution here tho: Apple broke the C++ 11 language standard by removing support for thread storage on OSX so AvanceDB doesn't build due to that.

However I've added to the backlog as #71.
